name: Deck Deployment

on:
  pull_request:
    branches:
      - main
    paths:
      - "teams/**"
      - "global/**"

  push:
    branches:
      - main
    paths:
      - "teams/**"
      - "global/**"

jobs:
  extract_changed_files:
    runs-on: deck
    name: Extract Changed Files
    outputs:
      changed_files: ${{ steps.changed-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v4

      - name: Get changed yaml files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files_ignore: ".github/**"
          files: |
            **.yaml

      - name: List all changed yaml files
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          echo "Changed yaml files:"
          for file in ${CHANGED_FILES}; do
            echo "$file was changed"
          done

  deck_commands:
    runs-on: deck
    name: Run decK commands
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    needs: extract_changed_files
    if: needs.extract_changed_files.outputs.changed_files != ''
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::471112575944:role/github-actions"
          aws-region: ap-south-1
      
      - name: Install decK
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.38.1/deck_1.38.1_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp
          sudo cp /tmp/deck /usr/local/bin/
          rm deck.tar.gz

      - name: Deck ping
        id: ping
        timeout-minutes: 2
        continue-on-error: false
        run: deck gateway ping --kong-addr ${{ secrets.KONG_ADDR }}
      
      - name: Deck validate
        id: validate
        env:
          CHANGED_FILES: ${{ needs.extract_changed_files.outputs.changed_files }}
        run: |
          deck gateway ping --kong-addr ${{ secrets.KONG_ADDR }}
          for file in ${CHANGED_FILES}; do
            deck gateway validate "$file" --kong-addr ${{ secrets.KONG_ADDR }}
          done

      - name: Deck diff
        id: diff
        timeout-minutes: 10
        if: github.event_name == 'pull_request'
        continue-on-error: false
        env:
          CHANGED_FILES: ${{ needs.extract_changed_files.outputs.changed_files }}
        run: |
          for file in ${CHANGED_FILES}; do
            echo "$file" >> deck-diff
            deck gateway diff "$file" --json-output >> deck-diff --kong-addr ${{ secrets.KONG_ADDR }}
          done

      - name: Format file
        id: show
        if: github.event_name == 'pull_request'
        continue-on-error: false
        run: |
          JSON_RESPONSE=$(cat deck-diff)
          echo "DECK_DIFF<<EOF" >> $GITHUB_ENV
          echo "$JSON_RESPONSE" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post comment for pull request
        if: github.event_name == 'pull_request'
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            ## 🔄 Kong Configuration Diff
            Here is the diff of the Kong configuration:

            ```diff
            ${{ env.DECK_DIFF }}
            ```

            **Note:** The changes above will be applied to the Kong configuration.

      - name: Dump current Kong configuration
        id: dump
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        continue-on-error: false
        run: |
          deck gateway dump --format yaml --output-file kong-backup.yaml --kong-addr ${{ secrets.KONG_ADDR }}

      - name: Deck sync
        id: sync
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        continue-on-error: true
        env:
          CHANGED_FILES: ${{ needs.extract_changed_files.outputs.changed_files }}
        run: |
          SYNC_FAILED=0
          for file in ${CHANGED_FILES}; do
            if ! deck gateway sync "$file" --kong-addr ${{ secrets.KONG_ADDR }}; then
              SYNC_FAILED=1
            fi
          done

          if [ $SYNC_FAILED -ne 0 ]; then
            echo "Sync failed. Proceeding to reset Kong configuration."
            deck gateway reset --kong-addr ${{ secrets.KONG_ADDR }}
            echo "Restoring previous configuration from dump file."
            deck gateway sync kong-backup.yaml --kong-addr ${{ secrets.KONG_ADDR }}
          else
            echo "Sync successful."
          fi
